---
include:
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle
  # - board: nice_nano_v2
  #   shield: cradio_right
  # - board: nice_nano_v2
  #   shield: cradio_left
  # - board: nice_nano_v2
  #   shield: settings_reset
